#!/usr/bin/env node
/**
 * scripts/dedupe-integrations.ts
 *
 * P3.3 — PREPARE-ONLY dedupe of the `Integration` table.
 *
 * Background: the Integration model (prisma/schema.prisma:195) has NO unique
 * constraint on (teamId, provider), so duplicate rows for the same team +
 * provider can exist today. This script collapses each duplicate group down
 * to the NEWEST row (createdAt desc, id desc tie-break) and deletes the rest.
 * The schema change (P3.3) adds `@@unique([teamId, provider])`; this script
 * MUST run BEFORE that migration or the migration will fail on the duplicate
 * rows still in the database.
 *
 * ── Run (dedupe FIRST, then migrate — ORDER MATTERS) ───────────────────────
 *   1. npx tsx --env-file=.env.local scripts/dedupe-integrations.ts
 *   2. npx prisma migrate dev --name integration_unique_team_provider
 *
 *   ⚠️ WARNING: the migration MUST run only AFTER this dedupe script.
 *      If the migration runs first, `CREATE UNIQUE INDEX` will fail with
 *      "could not create unique index ... duplicate key value violates
 *      unique constraint" on any duplicate (teamId, provider) rows.
 *
 * ── Expected migration SQL (generated by step 2, for reference) ────────────
 *   -- CreateIndex
 *   CREATE UNIQUE INDEX "Integration_teamId_provider_key"
 *   ON "Integration"("teamId", "provider");
 *
 * ── Behavior ───────────────────────────────────────────────────────────────
 *   - Idempotent: a second run finds zero duplicate groups and deletes nothing.
 *   - Safe on an empty DB: logs a zero summary and exits 0.
 *   - DB unreachable (e.g. Neon is down): logs a clear message and exits 1.
 *     The orchestrator will re-run this when the DB is back.
 *
 * Exit codes: 0 = success, 1 = failure (incl. unreachable DB).
 */
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

type DupGroup = {
  teamId: string;
  provider: string;
  count: number;
  keptId: string;
  deletedIds: string[];
};

async function main(): Promise<void> {
  // ── 1. Connect (fail softly but loudly if Neon is unreachable) ────────────
  try {
    await prisma.$connect();
  } catch (err) {
    console.error("[dedupe-integrations] DATABASE UNREACHABLE — dedupe skipped.");
    console.error(
      "[dedupe-integrations] Expected while the DB is down; the orchestrator will re-run this script when Neon is back."
    );
    console.error(
      `[dedupe-integrations] ${err instanceof Error ? err.message : String(err)}`
    );
    process.exitCode = 1;
    return;
  }

  try {
    // ── 2. Find (teamId, provider) groups with more than one row ────────────
    // groupBy + having(_count > 1) keeps this O(duplicate groups) instead of
    // pulling the whole table into memory.
    const dupKeys = await prisma.integration.groupBy({
      by: ["teamId", "provider"],
      _count: { _all: true },
      having: { teamId: { _count: { gt: 1 } } },
    });

    // ── 3. For each duplicate group: keep the NEWEST, queue the rest ────────
    const groups: DupGroup[] = [];
    for (const key of dupKeys) {
      const rows = await prisma.integration.findMany({
        where: { teamId: key.teamId, provider: key.provider },
        // createdAt desc = newest first; id desc is a deterministic
        // tie-break for rows with identical createdAt (cuid embeds a
        // timestamp, so newer ids sort higher).
        orderBy: [{ createdAt: "desc" }, { id: "desc" }],
        select: { id: true },
      });

      const keptId = rows[0].id;
      const deletedIds = rows.slice(1).map((r) => r.id);
      groups.push({
        teamId: key.teamId,
        provider: key.provider,
        count: rows.length,
        keptId,
        deletedIds,
      });
    }

    // ── 4. Delete the duplicates, per group, with logging ───────────────────
    let rowsKept = 0;
    let rowsDeleted = 0;
    for (const group of groups) {
      if (group.deletedIds.length === 0) continue;
      const res = await prisma.integration.deleteMany({
        where: { id: { in: group.deletedIds } },
      });
      rowsKept += 1;
      rowsDeleted += res.count;
      console.log(
        `[dedupe-integrations] team=${group.teamId} provider=${group.provider}: ` +
          `${group.count} rows → kept ${group.keptId}, deleted ${res.count} ` +
          `[${group.deletedIds.join(", ")}]`
      );
    }

    // ── 5. Summary ──────────────────────────────────────────────────────────
    console.log(
      `[dedupe-integrations] SUMMARY: ${groups.length} duplicate group(s) found, ` +
        `${rowsKept} row(s) kept, ${rowsDeleted} row(s) deleted.`
    );
    if (groups.length === 0) {
      console.log(
        "[dedupe-integrations] Nothing to do — table is clean (or empty)."
      );
    }
  } catch (err) {
    console.error(
      `[dedupe-integrations] FAILED: ${err instanceof Error ? err.message : String(err)}`
    );
    process.exitCode = 1;
  } finally {
    await prisma.$disconnect();
  }
}

main();
